services:
  database:
    container_name: database
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - eshop_volume:/var/lib/postgresql/data

  redis_eshop:
    container_name: redis_eshop
    ports:
      - 6380:6379
    volumes:
      - redis_eshop_volume:/data

  rabbitmq_eshop:
    container_name: rabbitmq_eshop
    env_file: ./.env
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq_eshop_volume:/var/lib/rabbitmq
