services:
  #  catalog.api:
  #    image: dducthang/eshop.catalog.api:v0.1
  #    build:
  #      context: .
  #      dockerfile: Catalog.API/Dockerfile
  #    ports:
  #      - 5001:5001
  #    depends_on:
  #      - database

  database:
    image: postgres:latest
  redis_eshop:
    image: redis:latest

volumes:
  eshop_volume:
  redis_eshop_volume:

  discount.api:
    image: discount.api
    build:
      context: .
      dockerfile: Discount.API/Dockerfile

  discount.grpc:
    image: discount.grpc
    build:
      context: .
      dockerfile: Discount.GRPC/Dockerfile

  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Basket.API/Dockerfile

  ordering.api:
    image: ordering.api
    build:
      context: .
      dockerfile: Ordering.API/Dockerfile
